---
extends: "@elastic/kibana"

settings:
  import/resolver:
    '@elastic/eslint-import-resolver-kibana':
      rootPackageName: 'comparable_time_range'
globals:
  angular: false

rules:
  keyword-spacing: error
